---
- name: Copy and configure inventory.ini to remote hosts
  hosts: vault
  become: true
  become_user: root
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    # - nginx_add_vhost
    - vault
    
