---
- name: Copy and configure inventory.ini to remote hosts
  hosts: localhost
  become: true
  become_user: root
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - vault_secret_operator
    # - nginx_add_vhost
    # - vault

    
