---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domain | first | replace('*.', '') }}/cert.pem
  register: letsencrypt_cert

- name: Ensure pre and post hook folders exist.
  file:
    path: /etc/letsencrypt/renewal-hooks/{{ item }}
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - pre
    - post

- name: Generate new certificate if one doesn't exist.
  command: certbot --non-interactive --nginx --agree-tos --redirect --email '{{ nginx_admin_email }}'  --domains "{{ cert_item.domain }}"
  when: not letsencrypt_cert.stat.exists
