---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install certbot and plugins
  apt:
    name: ["certbot", "python3-certbot-nginx"]
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Nginx
  apt:
    name: nginx
    state: present
- name: delete default nginx site
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: copy nginx nginx.conf without ssl
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ item.domain }}
    owner: root
    group: root
    mode: "0644"
  when: item.renew
  loop: "{{ nginx_domains }}"

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/{{ item.domain }}
    dest: /etc/nginx/sites-enabled/{{ item.domain }}
    state: link
  when: item.renew
  loop: "{{ nginx_domains }}"

- include_tasks: create-cert-standalone.yml
  when: cert_item.renew
  with_items: "{{ nginx_domains }}"
  loop_control:
    loop_var: cert_item
    
# - name: Restart nginx
#   service:
#     name: nginx
#     state: restarted
