- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Create prometheus group
  ansible.builtin.command:
    cmd: "groupadd --system prometheus"

- name: Create prometheus group
  ansible.builtin.command:
    cmd: "useradd -s /sbin/nologin --system -g prometheus prometheus"

- name: Creates directory prometheus
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory

- name: Creates directory prometheus
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory

- name: Download Prometheus binary release
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz"
    dest: "/root/prometheus-2.43.0.linux-amd64.tar.gz"

- name: Creates directory prometheus
  ansible.builtin.file:
    path: /root/prometheus
    state: directory

- name: Extract Prometheus tarball
  ansible.builtin.shell:
    cmd: "tar vxf /root/prometheus-2.43.0.linux-amd64.tar.gz -C /root/prometheus --strip-components=1"

- name: Move Prometheus binary
  ansible.builtin.command:
    cmd: "mv prometheus/prometheus /usr/local/bin"

- name: Move Prometheus binary
  ansible.builtin.command:
    cmd: "mv prometheus/promtool /usr/local/bin"

- name: Change ownership of prometheus binary
  ansible.builtin.command:
    cmd: "sudo chown prometheus:prometheus /usr/local/bin/prometheus"

- name: Change ownership of promtool binary
  ansible.builtin.command:
    cmd: "sudo chown prometheus:prometheus /usr/local/bin/promtool"

- name: Move consoles directory
  ansible.builtin.command:
    cmd: "sudo mv prometheus/consoles /etc/prometheus"

- name: Move console_libraries directory
  ansible.builtin.command:
    cmd: "sudo mv prometheus/console_libraries /etc/prometheus"

- name: Move prometheus.yml file
  ansible.builtin.command:
    cmd: "sudo mv prometheus/prometheus.yml /etc/prometheus"

- name: Change ownership of /etc/prometheus directory
  ansible.builtin.command:
    cmd: "sudo chown prometheus:prometheus /etc/prometheus"

- name: Change ownership of /etc/prometheus/consoles directory
  ansible.builtin.command:
    cmd: "sudo chown -R prometheus:prometheus /etc/prometheus/consoles"

- name: Change ownership of /etc/prometheus/console_libraries directory
  ansible.builtin.command:
    cmd: "sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries"

- name: Change ownership of /var/lib/prometheus directory
  ansible.builtin.command:
    cmd: "sudo chown -R prometheus:prometheus /var/lib/prometheus"

- name: Create Prometheus systemd service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service

- name: Reload systemd
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded

- name: Start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: started