---
############      installation vault for all server    ###############
- import_tasks: install-vault.yml
  when: inventory_hostname in ['leader', 'follower1', 'follower2']


# configuration of vault 
- name: Create Vault configuration file
  when: inventory_hostname in ['leader', 'follower1', 'follower2']
  template:
    src: "{{ 'vault.hcl_1' if inventory_hostname == 'leader' else ('vault.hcl_2' if inventory_hostname == 'follower1' else 'vault.hcl_3') }}"
    dest: /etc/vault.d/vault.hcl


- name: Ensure Vault service is started and enabled
  when: inventory_hostname in ['leader', 'follower1', 'follower2']
  become: true
  service:
    name: vault
    state: started
    enabled: true

- name: Run vault operator init leader 
  when: inventory_hostname == 'leader'
  command: vault operator init -address=http://127.0.0.1:8200
  register: vault_init_output

- set_fact:
    unseal_key_1: "{{ vault_init_output.stdout_lines[0].split(': ')[1] }}"
    unseal_key_2: "{{ vault_init_output.stdout_lines[1].split(': ')[1] }}"
    unseal_key_3: "{{ vault_init_output.stdout_lines[2].split(': ')[1] }}"
    unseal_key_4: "{{ vault_init_output.stdout_lines[3].split(': ')[1] }}"
    unseal_key_5: "{{ vault_init_output.stdout_lines[4].split(': ')[1] }}"
    root_token: "{{ vault_init_output.stdout_lines[6].split(': ')[1] }}"
  when: inventory_hostname == 'leader'

- name: Create /root/key file with unseal keys and root token
  when: inventory_hostname == 'leader' and save_unseal_file|bool
  ansible.builtin.copy:
    content: |
      Unseal Key 1: {{ unseal_key_1 }}
      Unseal Key 2: {{ unseal_key_2 }}
      Unseal Key 3: {{ unseal_key_3 }}
      Unseal Key 4: {{ unseal_key_4 }}
      Unseal Key 5: {{ unseal_key_5 }}
      Root Token: {{ root_token }}
    dest: /root/key

- name: Run vault operator join raft follower1 
  when: inventory_hostname == 'follower1'
  command: vault operator raft join -address="http://{{ vault_server_1 }}:8200" "http://{{ vault_server_1 }}:8200"

- name: Run vault operator join raft follower2 
  when: inventory_hostname == 'follower2'
  command: vault operator raft join -address="http://{{ vault_server_1 }}:8200" "http://{{ vault_server_1 }}:8200"

- name: Use variables from leader host
  debug:
    msg: |
      "Unseal Keys from leader: 
      - {{ hostvars['leader'].unseal_key_1 }}
      - {{ hostvars['leader'].unseal_key_2 }}
      - {{ hostvars['leader'].unseal_key_3 }}
      - {{ hostvars['leader'].unseal_key_4 }}
      - {{ hostvars['leader'].unseal_key_5 }}"


- name: Unseal Vault
  when: inventory_hostname in ['leader', 'follower1', 'follower2']
  ansible.builtin.shell:
    cmd: vault operator unseal -address="http://{{ vault_server_1 }}:8200" "{{ item }}"
  loop:
    - "{{ hostvars['leader'].unseal_key_1 }}"
    - "{{ hostvars['leader'].unseal_key_2 }}"
    - "{{ hostvars['leader'].unseal_key_3 }}"
  loop_control:
    loop_var: item
  
- name: Render unseal script
  when: inventory_hostname in ['leader', 'follower1', 'follower2'] and auto_unseal|bool 
  template:
    src: unseal_vault_template.j2
    dest: /usr/local/bin/unseal_vault.sh
    mode: '0755'
  vars:
    unseal_key_1: "{{ hostvars['leader'].unseal_key_1 }}"
    unseal_key_2: "{{ hostvars['leader'].unseal_key_2 }}"
    unseal_key_3: "{{ hostvars['leader'].unseal_key_3 }}"

- name: Ensure vault service file is present
  when: inventory_hostname in ['leader', 'follower1', 'follower2'] and auto_unseal|bool
  template:
    src: vault.service.j2
    dest: /usr/lib/systemd/system/vault.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd


#follower 1
- name: Run vault operator join raft to self follower1
  when: inventory_hostname == 'follower1'
  command: vault operator raft join  -address="http://127.0.0.1:8200" "http://{{ vault_server_1 }}:8200"

- name: Self Unseal Vault follower1  
  when: inventory_hostname == 'follower1'
  ansible.builtin.shell:
    cmd: vault operator unseal -address="http://127.0.0.1:8200" "{{ item }}"
  loop:
    - "{{ hostvars['leader'].unseal_key_1 }}"
    - "{{ hostvars['leader'].unseal_key_2 }}"
    - "{{ hostvars['leader'].unseal_key_3 }}"
  loop_control:
    loop_var: item

#follower 2
- name: Run vault operator join raft to self follower2
  when: inventory_hostname == 'follower2'
  command: vault operator raft join -address="http://127.0.0.1:8200" "http://{{ vault_server_1 }}:8200" 

- name: Self Unseal Vault follower2
  when: inventory_hostname == 'follower2'
  ansible.builtin.shell:
    cmd: vault operator unseal -address="http://127.0.0.1:8200" "{{ item }}"
  loop:
    - "{{ hostvars['leader'].unseal_key_1 }}"
    - "{{ hostvars['leader'].unseal_key_2 }}"
    - "{{ hostvars['leader'].unseal_key_3 }}"
  loop_control:
    loop_var: item